require('./jquery.slim')
require('./bootstrap')
require('../template/plugins/jquery/jquery.min');
require('../template/js/adminlte');
require('../template/js/dashboard');
require('../template/js/demo');
require('../template/plugins/bootstrap/js/bootstrap.bundle.min');
require('../template/plugins/morris/morris.min');
require('../template/plugins/sparkline/jquery.sparkline.min');
require('../template/plugins/jvectormap/jquery-jvectormap-1.2.2.min');
require('../template/plugins/jvectormap/jquery-jvectormap-world-mill-en');
require('../template/plugins/knob/jquery.knob');
require('../template/plugins/daterangepicker/daterangepicker');
require('../template/plugins/datepicker/bootstrap-datepicker');
require('../template/plugins/slimScroll/jquery.slimscroll.min');
require('../template/plugins/fastclick/fastclick');
